package dev.miladanbari.newsreader.view.news.model

data class ArticleItem(
    val source: SourceItem,
    val author: String?,
    val title: String,
    val description: String,
    val url: String,
    val urlToImage: String?,
    val publishedAt: String,
    val content: String,
    // This ID is defined for the purposes of the LazyColumn and should be unique for each item.
    // It can be replaced by a ID which is generated by the server.
    val id: Long = System.nanoTime(),
)

data class SourceItem(
    val id: String?,
    val name: String,
)
