package dev.miladanbari.newsreader.view.theme

import androidx.compose.ui.graphics.Color

// Light Colors
val md_theme_light_primary = Color(0xFF5B631D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E994)
val md_theme_light_onPrimaryContainer = Color(0xFF1A1E00)
val md_theme_light_secondary = Color(0xFF5E6144)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE3E5C1)
val md_theme_light_onSecondaryContainer = Color(0xFF1B1D07)
val md_theme_light_tertiary = Color(0xFF3B665A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBEECDD)
val md_theme_light_onTertiaryContainer = Color(0xFF002019)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFAED)
val md_theme_light_onBackground = Color(0xFF1C1C14)
val md_theme_light_surface = Color(0xFFFCFAED)
val md_theme_light_onSurface = Color(0xFF1C1C14)
val md_theme_light_surfaceVariant = Color(0xFFE4E3D2)
val md_theme_light_onSurfaceVariant = Color(0xFF47483B)
val md_theme_light_outline = Color(0xFF78786A)
val md_theme_light_outlineVariant = Color(0xFFC8C7B7)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF313128)
val md_theme_light_inverseOnSurface = Color(0xFFF3F1E4)
val md_theme_light_inversePrimary = Color(0xFFC4CD7B)
val md_theme_light_surfaceDim = Color(0xFFDCDACE)
val md_theme_light_surfaceBright = Color(0xFFFCFAED)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF6F4E7)
val md_theme_light_surfaceContainer = Color(0xFFF0EEE1)
val md_theme_light_surfaceContainerHigh = Color(0xFFEAE8DC)
val md_theme_light_surfaceContainerHighest = Color(0xFFE5E3D6)

// Dark Colors
val md_theme_dark_primary = Color(0xFFC4CD7B)
val md_theme_dark_onPrimary = Color(0xFF2E3300)
val md_theme_dark_primaryContainer = Color(0xFF444B05)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E994)
val md_theme_dark_secondary = Color(0xFFC7C9A7)
val md_theme_dark_onSecondary = Color(0xFF30321A)
val md_theme_dark_secondaryContainer = Color(0xFF46492E)
val md_theme_dark_onSecondaryContainer = Color(0xFFE3E5C1)
val md_theme_dark_tertiary = Color(0xFFA2D0C1)
val md_theme_dark_onTertiary = Color(0xFF06372D)
val md_theme_dark_tertiaryContainer = Color(0xFF234E43)
val md_theme_dark_onTertiaryContainer = Color(0xFFBEECDD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF13140D)
val md_theme_dark_onBackground = Color(0xFFE5E3D6)
val md_theme_dark_surface = Color(0xFF13140D)
val md_theme_dark_onSurface = Color(0xFFE5E3D6)
val md_theme_dark_surfaceVariant = Color(0xFF47483B)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C7B7)
val md_theme_dark_outline = Color(0xFF929282)
val md_theme_dark_outlineVariant = Color(0xFF47483B)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE5E3D6)
val md_theme_dark_inverseOnSurface = Color(0xFF313128)
val md_theme_dark_inversePrimary = Color(0xFF5B631D)
val md_theme_dark_surfaceDim = Color(0xFF13140D)
val md_theme_dark_surfaceBright = Color(0xFF393A31)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0E0F08)
val md_theme_dark_surfaceContainerLow = Color(0xFF1C1C14)
val md_theme_dark_surfaceContainer = Color(0xFF202018)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2A2B22)
val md_theme_dark_surfaceContainerHighest = Color(0xFF35352D)
